name: Tests
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Meson y Ninja
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build

      - name: Instalar libcjson-dev y pkgconf
        run: sudo apt-get install -y pkgconf libcjson-dev

      - name: Configurar build
        run: meson setup build
        working-directory: SERVIDOR

      - name: Compilar
        run: meson compile -C build
        working-directory: SERVIDOR

      - name: Correr tests
        run: meson test -C build
        working-directory: SERVIDOR

  test-cliente:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Correr tests del cliente
        run: dotnet test
        working-directory: CLIENTE/CLIENTE.Tests
